using System;

namespace SDL
{
	public enum KeyCode
	{
		Unknown = 0,

		Return    = '\r', 
		Escape    = '\x1b', 
		Backspace = '\b', 
		Tab       = '\t', 
		Space     = ' ', 
		Exclaim   = '!', 
		QuoteDbl  = '"', 
		Hash      = '#', 
		Percent   = '%', 
		Dollar    = '$', 
		Ampersand = '&', 
		Quote     = '\'', 
		LeftParen = '(', 
		RightParen = ')', 
		Asterisk = '*', 
		Plus = '+', 
		Comma = ',', 
		Minus = '-', 
		Period = '.', 
		Slash = '/', 
		_0 = '0', 
		_1 = '1', 
		_2 = '2', 
		_3 = '3', 
		_4 = '4', 
		_5 = '5', 
		_6 = '6', 
		_7 = '7', 
		_8 = '8', 
		_9 = '9', 
		Colon = ':', 
		SemiColon = ';', 
		Less = '<', 
		Equals = '=', 
		Greater = '>', 
		Question = '?', 
		At = '@', 
		LeftBracket = '[', 
		BackSlash = '\\', 
		RightBracket = ']', 
		Caret = '^', 
		Underscore = '_', 
		Backquote = '`', 
		a = 'a', 
		b = 'b', 
		c = 'c', 
		d = 'd', 
		e = 'e', 
		f = 'f', 
		g = 'g', 
		h = 'h', 
		i = 'i', 
		j = 'j', 
		k = 'k', 
		l = 'l', 
		m = 'm', 
		n = 'n', 
		o = 'o', 
		p = 'p', 
		q = 'q', 
		r = 'r', 
		s = 's', 
		t = 't', 
		u = 'u', 
		v = 'v', 
		w = 'w', 
		x = 'x', 
		y = 'y', 
		z = 'z', 

		Right = ScanCode.Right | (1 << 30), 
		Left  = ScanCode.Left | (1 << 30), 
		Down = ScanCode.Down | (1 << 30), 
		Up  = ScanCode.Up | (1 << 30)
	}
}